const express = require('express');
const router = express.Router();
const jwt = require("jsonwebtoken");


router.post("/create", (req,res)=>{
    const token = req.cookies.token;
    if(!token){
        res.status(401).json({
            message: "Unauthorized"
        })
    }

    // Check if the token is generated by our server

    try {
        jwt.verify(token,process.env.JWT_SECRET)
        
    } catch (error) {
        return res.status(401).json({
            message: "Token Is Invalid",
            error
        })
    }

    res.send("Post created successfully");
})

module.exports = router;
