const express = require('express');
const router = express.Router();
const jwt = require("jsonwebtoken");
const userModel = require('../models/user.model');


router.post("/create", async (req,res)=>{
    const token = req.cookies.token;
    if(!token){
        console.log(token)
        return res.status(401).json({
            message: "Unauthorized"
        })
    }

    // Check if the token is generated by our server

    try {
        const decoded = jwt.verify(token,process.env.JWT_SECRET)
        console.log(decoded);

        const user = await userModel.findOne({
            _id: decoded.id
        })

        console.log(user);
        
    } catch (error) {
        return res.status(401).json({
            message: "Token Is Invalid",
            error
        })
    }

    return res.send("Post created successfully");
})

module.exports = router;
